OFN_TYPE = "typ"
OFN_SUBJECT_TYPE = "typ subjektu"
OFN_OBJECT_TYPE = "typ objektu"
OFN_TROPE_TYPE = "typ vlastnosti"
OFN_DEFINITION = "definice"
OFN_DESCRIPTION = "popis"
OFN_RELATION = "zdroj"
OFN_DATATYPE = "datový typ"
