MULTIPLE_VALUE_SEPARATOR = ";"
YES = "Ano"
NO = "Ne"
DEFAULT_LANGUAGE = "cs"

SHEET_VOCABULARY = "Slovník"
SHEET_CLASS = "Subjekty a objekty práva"
SHEET_TROPE = "Vlastnosti"
SHEET_RELATIONSHIP = "Vztahy"

OFN_LKOD = "Adresa lokálního katalogu dat, ve kterém bude slovník registrován"
OFN_NAME = "Název"
OFN_TYPE = "Typ"
OFN_SUBCLASS = "Nadřazený pojem"
OFN_EQUIVALENT = "Ekvivalentní pojem"
OFN_DEFINITION = "Definice"
OFN_DESCRIPTION = "Popis"
OFN_SOURCE = "Zdroj"
OFN_DATATYPE = "Datový typ"
OFN_RELATED = "Související zdroj"
OFN_ALTERNATIVE = "Alternativní název"
OFN_SUBJECT_TYPE = "Typ subjektu"
OFN_OBJECT_TYPE = "Typ objektu"
OFN_TROPE_TYPE = "Typ vlastnosti"
OFN_SUBJECT = "Subjekt práva"
OFN_OBJECT = "Objekt práva"
OFN_SUBJECT_OR_OBJECT = "Subjekt nebo objekt práva"
OFN_IRI = "Identifikátor"

OFN_RPP_AIS = "Agendový informační systém"
OFN_RPP_AGENDA = "Agenda"
OFN_RPP_TYPE = "Je pojem veřejný?"
OFN_RPP_SHARED = "Je pojem sdílen v PPDF?"
OFN_RPP_PRIVATE_SOURCE = "Ustanovení dokládající neveřejnost"
